apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: sokolozen/product
      context: product
      sync:
        manual:
          - src: "index.ts"
            dest: .
          - src: "app/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile


