apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-depl
  labels:
    app: product
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: sokolozen/product
          ports:
          - containerPort: 80
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-productdb
            - name: POSTGRES_TEST_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-test-productdb
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_HOST
              value: "host.docker.internal"
---
apiVersion: v1
kind: Service
metadata:
  name: product-srv
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
