apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-depl
  labels:
    app: stock
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: stock
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
        - name: stock
          image: sokolozen/stock
          ports:
          - containerPort: 3000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-stockdb
            - name: POSTGRES_TEST_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-test-stockdb
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_HOST
              value: "host.docker.internal"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-host
---
apiVersion: v1
kind: Service
metadata:
  name: stock-srv
spec:
  selector:
    app: stock
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
